// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlfxblhiqckmwbvjpjhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sZnhibGhpcWNrbXdidmpwamhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NzUzMDcsImV4cCI6MjA3MjU1MTMwN30.qK-gLKhzE0GBDVWsyowp4_i6X1THa17nSz6YHbZ7Bpg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});